#!/bin/bash
# Docker entrypoint for amplifier-distro.
#
# Auto-initializes config and exports API keys from environment,
# then exec's the target command (uvicorn, bash, amplifier-tui, etc.)
#
# Signal handling: the final `exec "$@"` replaces this shell with the
# target process so it receives SIGTERM directly from Docker.

set -e

# ── Auto-initialize if not already configured ────────────────────
# Uses AMPLIFIER_HOME from environment or falls back to ~/.amplifier
# (matches conventions.AMPLIFIER_HOME).
AMPLIFIER_HOME="${AMPLIFIER_HOME:-$HOME/.amplifier}"
AMPLIFIER_DISTRO_HOME="${AMPLIFIER_DISTRO_HOME:-$HOME/.amplifier-distro}"
DISTRO_CONFIG="$AMPLIFIER_DISTRO_HOME/settings.yaml"

if [ ! -f "$DISTRO_CONFIG" ]; then
    echo "[entrypoint] No distro.yaml found, creating default config..."
    mkdir -p "$AMPLIFIER_HOME/memory" \
             "$AMPLIFIER_HOME/cache" \
             "$AMPLIFIER_HOME/projects" \
             "$AMPLIFIER_HOME/server" \
             "$AMPLIFIER_HOME/bundles"
    cat > "$DISTRO_CONFIG" <<EOF
# Auto-generated by docker-entrypoint.sh
workspace_root: ${WORKSPACE_ROOT:-$HOME/dev}
identity:
  github_handle: ${GITHUB_HANDLE:-docker}
  git_email: ${GIT_EMAIL:-docker@amplifier.local}
EOF
    echo "[entrypoint] Created $DISTRO_CONFIG"
fi

# ── Export API keys from environment to keys.env ─────────────────
# In Docker, secrets arrive as env vars. Write them to keys.env
# (conventions.KEYS_FILENAME) so the distro server can find them.
KEYS_FILE="$AMPLIFIER_HOME/keys.env"

if [ ! -f "$KEYS_FILE" ]; then
    _wrote_key=false
    for var in ANTHROPIC_API_KEY OPENAI_API_KEY GITHUB_TOKEN \
               SLACK_BOT_TOKEN SLACK_APP_TOKEN SLACK_SIGNING_SECRET; do
        val=$(eval echo "\${$var:-}")
        if [ -n "$val" ] && [ "$val" != "test-fake-key-for-testing" ] \
           && [ "$val" != "sk-test-fake-key-for-testing" ] \
           && [ "$val" != "ghp-test-fake-token" ]; then
            if [ "$_wrote_key" = false ]; then
                echo "# Auto-generated by docker-entrypoint.sh" > "$KEYS_FILE"
                _wrote_key=true
            fi
            echo "$var=\"$val\"" >> "$KEYS_FILE"
        fi
    done
    if [ "$_wrote_key" = true ]; then
        chmod 600 "$KEYS_FILE"
        echo "[entrypoint] Exported API keys to $KEYS_FILE"
    fi
fi

exec "$@"
